# Docker compose version
version: "3"

services:
  node:
    container_name: dashboard-v2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "3001:3000"
